import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Music Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  // RootLayout ek input parameter expect kar raha hai and i.e. children and we displayed here children {children} inside return
  children,
}: Readonly<{
  // here type is being defined
  // this is typescript
  // here type is Readonly and do not mess with it
  children: React.ReactNode;//and the children hai uska type is React.ReactNode mean kis tarah type ko accept kar rahe ho and here we are accepting React.ReactNode like we have string type , number's type and similar we have react ka React.ReactNode type hai
}>) {
  return (
    // here we need to add dark class
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full flex items-center justify-center ">
          <Navbar />
        </div>
        {/* <h2>Nav Item</h2> */}
        {children}
      </body>
    </html>
  );
}
// The entire frontend code is shipped to user's browser but backend code should never be shipped to user's browser or nahi hi hota hai. So in next js, gives you the capability to write the backend code right here means in this framework and I will keep in mind that code will never ship to user's browser.

//children comes from page means the elements you design in page that will come to layout.
